#!/usr/bin/env python
"""
Exploits the Theremini's pitch-correction to play something random, but will
hopefully sound ok
"""

import rospy
from theremini_player.random_player import RandomPlayer

if __name__=='__main__':
    rospy.init_node('random_theremin')
    player = RandomPlayer()
    player.run()
